ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
UPDATE customers SET created_at = COALESCE(created_at, NOW()) WHERE created_at IS NULL;
UPDATE customers SET updated_at = COALESCE(updated_at, NOW()) WHERE updated_at IS NULL;
ALTER TABLE IF EXISTS customers ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS customers ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS customers ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE IF EXISTS customers ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE IF EXISTS loan_products ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE IF EXISTS loan_products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
UPDATE loan_products SET created_at = COALESCE(created_at, NOW()) WHERE created_at IS NULL;
UPDATE loan_products SET updated_at = COALESCE(updated_at, NOW()) WHERE updated_at IS NULL;
ALTER TABLE IF EXISTS loan_products ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS loan_products ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS loan_products ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE IF EXISTS loan_products ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE IF EXISTS loan_accounts ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE IF EXISTS loan_accounts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
UPDATE loan_accounts SET created_at = COALESCE(created_at, NOW()) WHERE created_at IS NULL;
UPDATE loan_accounts SET updated_at = COALESCE(updated_at, NOW()) WHERE updated_at IS NULL;
ALTER TABLE IF EXISTS loan_accounts ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS loan_accounts ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS loan_accounts ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE IF EXISTS loan_accounts ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE IF EXISTS emi_payments ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE IF EXISTS emi_payments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
UPDATE emi_payments SET created_at = COALESCE(created_at, NOW()) WHERE created_at IS NULL;
UPDATE emi_payments SET updated_at = COALESCE(updated_at, NOW()) WHERE updated_at IS NULL;
ALTER TABLE IF EXISTS emi_payments ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS emi_payments ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS emi_payments ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE IF EXISTS emi_payments ALTER COLUMN updated_at SET NOT NULL;
