"use strict";
var nums = [a, b, c, d];
console.log(nums[0]);
console.log(nums[1]);
console.log(nums[2]);
console.log(nums[3]);
var alphabets;
alphabets = ["a", "b", "c", "d"];
console.log(alphabets[0]);
console.log(alphabets[1]);
